export const categories = [
	{ id: 1, text: 'Uncategorized' },
	{ id: 2, text: 'Coffee' },
	{ id: 3, text: 'Groceries' },
	{ id: 4, text: 'Shopping' },
	{ id: 5, text: 'Electronics' },
	{ id: 6, text: 'Gas' },
	{ id: 7, text: 'Transportation' },
	{ id: 8, text: 'Entertainment' },
	{ id: 9, text: 'Food' },
	{ id: 10, text: 'Housing' },
	{ id: 11, text: 'Utilities' },
	{ id: 12, text: 'Income' },
	{ id: 13, text: 'Transfer' },
	{ id: 14, text: 'Healthcare' },
	{ id: 15, text: 'Home Improvement' },
	{ id: 16, text: 'Software' },
	{ id: 17, text: 'Clothing' },
	{ id: 18, text: 'Gifts' }
];

// Auto-categorization rules

export const categorizationRules = {
  'STARBUCKS': 'Coffee',
  'COFFEE BEAN': 'Coffee',
  'DUNKIN': 'Coffee',
  'WHOLE FOODS': 'Groceries',
  'SAFEWAY': 'Groceries',
  'TRADER JOES': 'Groceries',
  'KROGER': 'Groceries',
  'COSTCO': 'Groceries',
  'TARGET': 'Shopping',
  'AMAZON': 'Shopping',
  'BEST BUY': 'Electronics',
  'SHELL': 'Gas',
  'CHEVRON': 'Gas',
  'TEXACO': 'Gas',
  'UBER': 'Transportation',
  'LYFT': 'Transportation',
  'NETFLIX': 'Entertainment',
  'SPOTIFY': 'Entertainment',
  'AMAZON PRIME': 'Entertainment',
  'STEAM': 'Entertainment',
  'CHIPOTLE': 'Food',
  'MCDONALDS': 'Food',
  'DOMINOS': 'Food',
  'TACO BELL': 'Food',
  'PANDA EXPRESS': 'Food',
  'IN-N-OUT': 'Food',
  'JIMMY JOHNS': 'Food',
  'DOORDASH': 'Food',
  'UBER EATS': 'Food',
  'RENT': 'Housing',
  'ELECTRIC': 'Utilities',
  'VERIZON': 'Utilities',
  'SALARY': 'Income',
  'PAYPAL': 'Transfer',
  'VENMO': 'Transfer',
  'TAX REFUND': 'Income',
  'CVS': 'Healthcare',
  'WALGREENS': 'Healthcare',
  'HOME DEPOT': 'Home Improvement',
  'LOWE\'S': 'Home Improvement',
  'ADOBE': 'Software',
  'ZOOM': 'Software',
  'GITHUB': 'Software',
  'MACY\'S': 'Clothing',
  'FLOWERS': 'Gifts'
};
